In [1]:
from pathlib import Path
from typing import cast

import numpy as np
import pandas as pd
from scipy.io.arff import loadarff

%load_ext autoreload
%autoreload 2
import ml_project.data as d
import ml_project.helpers as h

In [2]:
ds = d.Dataset(Path("../data/15s.arff"))

In [3]:
ds.numerical5

         duration        pps          bps  max_flowiat   mean_flowiat  cls
0       9368711.0  10.353612  4802.688438    1523088.0   97590.739583    2
1       7340238.0  11.580006  4340.186245    1517774.0   87383.785714    2
2       4644225.0  11.412022  4161.512416    1079974.0   89312.019231    2
3       4978735.0   8.034169  3918.666087    2441990.0  127659.871795    2
4      11838189.0   7.602514  2802.540152    3042717.0  133013.359551    2
...           ...        ...          ...          ...            ...  ...
18753     73240.0  27.307482  6116.876024      73240.0   73240.000000    6
18754     52083.0  38.400246  8601.655051      52083.0   52083.000000    6
18755     67923.0  29.445107  6595.703959      67923.0   67923.000000    6
18756    313588.0   6.377795  1428.626095     313588.0  313588.000000    6
18757     76386.0  26.182808  5864.949074      76386.0   76386.000000    6

[18226 rows x 6 columns]

In [4]:
ds.class_fraction(ds.numerical5)

                      pop  pop_f      f
BROWSING (1)         2500   13.7  100.0
CHAT (2)              888    4.9   99.8
STREAMING (3)         451    2.5   93.6
MAIL (4)              245    1.3   98.4
VOIP (5)             2820   15.5   99.8
P2P (6)               993    5.4   99.3
FT (7)                862    4.7   84.7
VPN-VOIP (8)         2265   12.4   99.7
VPN-CHAT (9)         1163    6.4   97.2
VPN-STREAMING (10)    474    2.6   99.8
VPN-FT (11)          1911   10.5   98.9
VPN-BROWSING (12)    2500   13.7  100.0
VPN-P2P (13)          665    3.6   71.7
VPN-MAIL (14)         489    2.7   99.6
all                 18226  100.0   97.2

In [5]:
# pd.plotting.scatter_matrix(ds.numerical5, figsize=(20, 20))

In [6]:
corr = ds.numerical5.corr()
corr.style.format(precision=2).background_gradient(cmap='coolwarm')

In [7]:
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier


def try_knn(df):
    # TODO: stratify
    train, test = train_test_split(df)

    cl = KNeighborsClassifier()
    cl.fit(train.drop(columns="cls"), train["cls"])
    p = cl.predict(test.drop(columns="cls"))
    return accuracy_score(test["cls"], p)

In [8]:
[try_knn(ds.orig) for _ in range(5)]

[0.6991471215351812,
 0.7029850746268657,
 0.6968017057569297,
 0.6874200426439232,
 0.7049040511727079]

In [9]:
[try_knn(ds.with_dur) for _ in range(5)]

[0.706166337502743,
 0.7103357472021067,
 0.7000219442615756,
 0.7050691244239631,
 0.7028746982664034]

In [10]:
[try_knn(ds.numerical5) for _ in range(5)]

[0.6644722405091069,
 0.662936142198815,
 0.6554750932631117,
 0.6548167654158438,
 0.6469168312486285]

In [11]:
[try_knn(ds.flagged) for _ in range(5)]

[0.6618389291200351,
 0.6453807329383366,
 0.6543778801843319,
 0.6554750932631117,
 0.6607417160412552]

In [12]:
[try_knn(ds.drop_missing) for _ in range(5)]

[0.6893390191897655,
 0.6901918976545842,
 0.7040511727078891,
 0.7110874200426439,
 0.7012793176972282]